// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bot.proto

package bot // import "v2.staffjoy.com/bot"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import company "v2.staffjoy.com/company"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type OnboardWorkerRequest struct {
	CompanyUuid          string   `protobuf:"bytes,1,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	UserUuid             string   `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnboardWorkerRequest) Reset()         { *m = OnboardWorkerRequest{} }
func (m *OnboardWorkerRequest) String() string { return proto.CompactTextString(m) }
func (*OnboardWorkerRequest) ProtoMessage()    {}
func (*OnboardWorkerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bot_38c84d5f33f64b69, []int{0}
}
func (m *OnboardWorkerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnboardWorkerRequest.Unmarshal(m, b)
}
func (m *OnboardWorkerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnboardWorkerRequest.Marshal(b, m, deterministic)
}
func (dst *OnboardWorkerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnboardWorkerRequest.Merge(dst, src)
}
func (m *OnboardWorkerRequest) XXX_Size() int {
	return xxx_messageInfo_OnboardWorkerRequest.Size(m)
}
func (m *OnboardWorkerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OnboardWorkerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OnboardWorkerRequest proto.InternalMessageInfo

func (m *OnboardWorkerRequest) GetCompanyUuid() string {
	if m != nil {
		return m.CompanyUuid
	}
	return ""
}

func (m *OnboardWorkerRequest) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

type AlertNewShiftOptimizedRequest struct {
	UserName             string               `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserPhNum            string               `protobuf:"bytes,2,opt,name=user_ph_num,json=userPhNum,proto3" json:"user_ph_num,omitempty"`
	UserEmail            string               `protobuf:"bytes,3,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	JobName              string               `protobuf:"bytes,4,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	TeamTimezone         string               `protobuf:"bytes,5,opt,name=team_timezone,json=teamTimezone,proto3" json:"team_timezone,omitempty"`
	ShiftStart           *timestamp.Timestamp `protobuf:"bytes,6,opt,name=shift_start,json=shiftStart,proto3" json:"shift_start,omitempty"`
	ShiftStop            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=shift_stop,json=shiftStop,proto3" json:"shift_stop,omitempty"`
	CompanyName          string               `protobuf:"bytes,8,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AlertNewShiftOptimizedRequest) Reset()         { *m = AlertNewShiftOptimizedRequest{} }
func (m *AlertNewShiftOptimizedRequest) String() string { return proto.CompactTextString(m) }
func (*AlertNewShiftOptimizedRequest) ProtoMessage()    {}
func (*AlertNewShiftOptimizedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bot_38c84d5f33f64b69, []int{1}
}
func (m *AlertNewShiftOptimizedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertNewShiftOptimizedRequest.Unmarshal(m, b)
}
func (m *AlertNewShiftOptimizedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertNewShiftOptimizedRequest.Marshal(b, m, deterministic)
}
func (dst *AlertNewShiftOptimizedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertNewShiftOptimizedRequest.Merge(dst, src)
}
func (m *AlertNewShiftOptimizedRequest) XXX_Size() int {
	return xxx_messageInfo_AlertNewShiftOptimizedRequest.Size(m)
}
func (m *AlertNewShiftOptimizedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertNewShiftOptimizedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AlertNewShiftOptimizedRequest proto.InternalMessageInfo

func (m *AlertNewShiftOptimizedRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *AlertNewShiftOptimizedRequest) GetUserPhNum() string {
	if m != nil {
		return m.UserPhNum
	}
	return ""
}

func (m *AlertNewShiftOptimizedRequest) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

func (m *AlertNewShiftOptimizedRequest) GetJobName() string {
	if m != nil {
		return m.JobName
	}
	return ""
}

func (m *AlertNewShiftOptimizedRequest) GetTeamTimezone() string {
	if m != nil {
		return m.TeamTimezone
	}
	return ""
}

func (m *AlertNewShiftOptimizedRequest) GetShiftStart() *timestamp.Timestamp {
	if m != nil {
		return m.ShiftStart
	}
	return nil
}

func (m *AlertNewShiftOptimizedRequest) GetShiftStop() *timestamp.Timestamp {
	if m != nil {
		return m.ShiftStop
	}
	return nil
}

func (m *AlertNewShiftOptimizedRequest) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

type AlertNewShiftRequest struct {
	UserUuid             string         `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	NewShift             *company.Shift `protobuf:"bytes,2,opt,name=new_shift,json=newShift,proto3" json:"new_shift,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AlertNewShiftRequest) Reset()         { *m = AlertNewShiftRequest{} }
func (m *AlertNewShiftRequest) String() string { return proto.CompactTextString(m) }
func (*AlertNewShiftRequest) ProtoMessage()    {}
func (*AlertNewShiftRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bot_38c84d5f33f64b69, []int{2}
}
func (m *AlertNewShiftRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertNewShiftRequest.Unmarshal(m, b)
}
func (m *AlertNewShiftRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertNewShiftRequest.Marshal(b, m, deterministic)
}
func (dst *AlertNewShiftRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertNewShiftRequest.Merge(dst, src)
}
func (m *AlertNewShiftRequest) XXX_Size() int {
	return xxx_messageInfo_AlertNewShiftRequest.Size(m)
}
func (m *AlertNewShiftRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertNewShiftRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AlertNewShiftRequest proto.InternalMessageInfo

func (m *AlertNewShiftRequest) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *AlertNewShiftRequest) GetNewShift() *company.Shift {
	if m != nil {
		return m.NewShift
	}
	return nil
}

type AlertNewShiftsRequest struct {
	UserUuid             string           `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	NewShifts            []*company.Shift `protobuf:"bytes,2,rep,name=new_shifts,json=newShifts,proto3" json:"new_shifts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AlertNewShiftsRequest) Reset()         { *m = AlertNewShiftsRequest{} }
func (m *AlertNewShiftsRequest) String() string { return proto.CompactTextString(m) }
func (*AlertNewShiftsRequest) ProtoMessage()    {}
func (*AlertNewShiftsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bot_38c84d5f33f64b69, []int{3}
}
func (m *AlertNewShiftsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertNewShiftsRequest.Unmarshal(m, b)
}
func (m *AlertNewShiftsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertNewShiftsRequest.Marshal(b, m, deterministic)
}
func (dst *AlertNewShiftsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertNewShiftsRequest.Merge(dst, src)
}
func (m *AlertNewShiftsRequest) XXX_Size() int {
	return xxx_messageInfo_AlertNewShiftsRequest.Size(m)
}
func (m *AlertNewShiftsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertNewShiftsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AlertNewShiftsRequest proto.InternalMessageInfo

func (m *AlertNewShiftsRequest) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *AlertNewShiftsRequest) GetNewShifts() []*company.Shift {
	if m != nil {
		return m.NewShifts
	}
	return nil
}

type AlertRemovedShiftRequest struct {
	UserUuid             string         `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	OldShift             *company.Shift `protobuf:"bytes,2,opt,name=old_shift,json=oldShift,proto3" json:"old_shift,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AlertRemovedShiftRequest) Reset()         { *m = AlertRemovedShiftRequest{} }
func (m *AlertRemovedShiftRequest) String() string { return proto.CompactTextString(m) }
func (*AlertRemovedShiftRequest) ProtoMessage()    {}
func (*AlertRemovedShiftRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bot_38c84d5f33f64b69, []int{4}
}
func (m *AlertRemovedShiftRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertRemovedShiftRequest.Unmarshal(m, b)
}
func (m *AlertRemovedShiftRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertRemovedShiftRequest.Marshal(b, m, deterministic)
}
func (dst *AlertRemovedShiftRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertRemovedShiftRequest.Merge(dst, src)
}
func (m *AlertRemovedShiftRequest) XXX_Size() int {
	return xxx_messageInfo_AlertRemovedShiftRequest.Size(m)
}
func (m *AlertRemovedShiftRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertRemovedShiftRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AlertRemovedShiftRequest proto.InternalMessageInfo

func (m *AlertRemovedShiftRequest) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *AlertRemovedShiftRequest) GetOldShift() *company.Shift {
	if m != nil {
		return m.OldShift
	}
	return nil
}

type AlertRemovedShiftsRequest struct {
	UserUuid             string           `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	OldShifts            []*company.Shift `protobuf:"bytes,2,rep,name=old_shifts,json=oldShifts,proto3" json:"old_shifts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AlertRemovedShiftsRequest) Reset()         { *m = AlertRemovedShiftsRequest{} }
func (m *AlertRemovedShiftsRequest) String() string { return proto.CompactTextString(m) }
func (*AlertRemovedShiftsRequest) ProtoMessage()    {}
func (*AlertRemovedShiftsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bot_38c84d5f33f64b69, []int{5}
}
func (m *AlertRemovedShiftsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertRemovedShiftsRequest.Unmarshal(m, b)
}
func (m *AlertRemovedShiftsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertRemovedShiftsRequest.Marshal(b, m, deterministic)
}
func (dst *AlertRemovedShiftsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertRemovedShiftsRequest.Merge(dst, src)
}
func (m *AlertRemovedShiftsRequest) XXX_Size() int {
	return xxx_messageInfo_AlertRemovedShiftsRequest.Size(m)
}
func (m *AlertRemovedShiftsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertRemovedShiftsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AlertRemovedShiftsRequest proto.InternalMessageInfo

func (m *AlertRemovedShiftsRequest) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *AlertRemovedShiftsRequest) GetOldShifts() []*company.Shift {
	if m != nil {
		return m.OldShifts
	}
	return nil
}

type AlertChangedShiftRequest struct {
	UserUuid             string         `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	OldShift             *company.Shift `protobuf:"bytes,2,opt,name=old_shift,json=oldShift,proto3" json:"old_shift,omitempty"`
	NewShift             *company.Shift `protobuf:"bytes,3,opt,name=new_shift,json=newShift,proto3" json:"new_shift,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AlertChangedShiftRequest) Reset()         { *m = AlertChangedShiftRequest{} }
func (m *AlertChangedShiftRequest) String() string { return proto.CompactTextString(m) }
func (*AlertChangedShiftRequest) ProtoMessage()    {}
func (*AlertChangedShiftRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bot_38c84d5f33f64b69, []int{6}
}
func (m *AlertChangedShiftRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertChangedShiftRequest.Unmarshal(m, b)
}
func (m *AlertChangedShiftRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertChangedShiftRequest.Marshal(b, m, deterministic)
}
func (dst *AlertChangedShiftRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertChangedShiftRequest.Merge(dst, src)
}
func (m *AlertChangedShiftRequest) XXX_Size() int {
	return xxx_messageInfo_AlertChangedShiftRequest.Size(m)
}
func (m *AlertChangedShiftRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertChangedShiftRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AlertChangedShiftRequest proto.InternalMessageInfo

func (m *AlertChangedShiftRequest) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *AlertChangedShiftRequest) GetOldShift() *company.Shift {
	if m != nil {
		return m.OldShift
	}
	return nil
}

func (m *AlertChangedShiftRequest) GetNewShift() *company.Shift {
	if m != nil {
		return m.NewShift
	}
	return nil
}

func init() {
	proto.RegisterType((*OnboardWorkerRequest)(nil), "staffjoy.bot.OnboardWorkerRequest")
	proto.RegisterType((*AlertNewShiftOptimizedRequest)(nil), "staffjoy.bot.AlertNewShiftOptimizedRequest")
	proto.RegisterType((*AlertNewShiftRequest)(nil), "staffjoy.bot.AlertNewShiftRequest")
	proto.RegisterType((*AlertNewShiftsRequest)(nil), "staffjoy.bot.AlertNewShiftsRequest")
	proto.RegisterType((*AlertRemovedShiftRequest)(nil), "staffjoy.bot.AlertRemovedShiftRequest")
	proto.RegisterType((*AlertRemovedShiftsRequest)(nil), "staffjoy.bot.AlertRemovedShiftsRequest")
	proto.RegisterType((*AlertChangedShiftRequest)(nil), "staffjoy.bot.AlertChangedShiftRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BotServiceClient is the client API for BotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BotServiceClient interface {
	OnboardWorker(ctx context.Context, in *OnboardWorkerRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	AlertNewShift(ctx context.Context, in *AlertNewShiftRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	AlertNewShiftOptimized(ctx context.Context, in *AlertNewShiftOptimizedRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	AlertNewShifts(ctx context.Context, in *AlertNewShiftsRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	AlertRemovedShift(ctx context.Context, in *AlertRemovedShiftRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	AlertRemovedShifts(ctx context.Context, in *AlertRemovedShiftsRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	AlertChangedShift(ctx context.Context, in *AlertChangedShiftRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type botServiceClient struct {
	cc *grpc.ClientConn
}

func NewBotServiceClient(cc *grpc.ClientConn) BotServiceClient {
	return &botServiceClient{cc}
}

func (c *botServiceClient) OnboardWorker(ctx context.Context, in *OnboardWorkerRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/staffjoy.bot.BotService/OnboardWorker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) AlertNewShift(ctx context.Context, in *AlertNewShiftRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/staffjoy.bot.BotService/AlertNewShift", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) AlertNewShiftOptimized(ctx context.Context, in *AlertNewShiftOptimizedRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/staffjoy.bot.BotService/AlertNewShiftOptimized", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) AlertNewShifts(ctx context.Context, in *AlertNewShiftsRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/staffjoy.bot.BotService/AlertNewShifts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) AlertRemovedShift(ctx context.Context, in *AlertRemovedShiftRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/staffjoy.bot.BotService/AlertRemovedShift", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) AlertRemovedShifts(ctx context.Context, in *AlertRemovedShiftsRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/staffjoy.bot.BotService/AlertRemovedShifts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) AlertChangedShift(ctx context.Context, in *AlertChangedShiftRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/staffjoy.bot.BotService/AlertChangedShift", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotServiceServer is the server API for BotService service.
type BotServiceServer interface {
	OnboardWorker(context.Context, *OnboardWorkerRequest) (*empty.Empty, error)
	AlertNewShift(context.Context, *AlertNewShiftRequest) (*empty.Empty, error)
	AlertNewShiftOptimized(context.Context, *AlertNewShiftOptimizedRequest) (*empty.Empty, error)
	AlertNewShifts(context.Context, *AlertNewShiftsRequest) (*empty.Empty, error)
	AlertRemovedShift(context.Context, *AlertRemovedShiftRequest) (*empty.Empty, error)
	AlertRemovedShifts(context.Context, *AlertRemovedShiftsRequest) (*empty.Empty, error)
	AlertChangedShift(context.Context, *AlertChangedShiftRequest) (*empty.Empty, error)
}

func RegisterBotServiceServer(s *grpc.Server, srv BotServiceServer) {
	s.RegisterService(&_BotService_serviceDesc, srv)
}

func _BotService_OnboardWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnboardWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).OnboardWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staffjoy.bot.BotService/OnboardWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).OnboardWorker(ctx, req.(*OnboardWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_AlertNewShift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertNewShiftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).AlertNewShift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staffjoy.bot.BotService/AlertNewShift",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).AlertNewShift(ctx, req.(*AlertNewShiftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_AlertNewShiftOptimized_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertNewShiftOptimizedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).AlertNewShiftOptimized(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staffjoy.bot.BotService/AlertNewShiftOptimized",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).AlertNewShiftOptimized(ctx, req.(*AlertNewShiftOptimizedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_AlertNewShifts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertNewShiftsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).AlertNewShifts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staffjoy.bot.BotService/AlertNewShifts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).AlertNewShifts(ctx, req.(*AlertNewShiftsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_AlertRemovedShift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertRemovedShiftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).AlertRemovedShift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staffjoy.bot.BotService/AlertRemovedShift",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).AlertRemovedShift(ctx, req.(*AlertRemovedShiftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_AlertRemovedShifts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertRemovedShiftsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).AlertRemovedShifts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staffjoy.bot.BotService/AlertRemovedShifts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).AlertRemovedShifts(ctx, req.(*AlertRemovedShiftsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_AlertChangedShift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertChangedShiftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).AlertChangedShift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staffjoy.bot.BotService/AlertChangedShift",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).AlertChangedShift(ctx, req.(*AlertChangedShiftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BotService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "staffjoy.bot.BotService",
	HandlerType: (*BotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnboardWorker",
			Handler:    _BotService_OnboardWorker_Handler,
		},
		{
			MethodName: "AlertNewShift",
			Handler:    _BotService_AlertNewShift_Handler,
		},
		{
			MethodName: "AlertNewShiftOptimized",
			Handler:    _BotService_AlertNewShiftOptimized_Handler,
		},
		{
			MethodName: "AlertNewShifts",
			Handler:    _BotService_AlertNewShifts_Handler,
		},
		{
			MethodName: "AlertRemovedShift",
			Handler:    _BotService_AlertRemovedShift_Handler,
		},
		{
			MethodName: "AlertRemovedShifts",
			Handler:    _BotService_AlertRemovedShifts_Handler,
		},
		{
			MethodName: "AlertChangedShift",
			Handler:    _BotService_AlertChangedShift_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bot.proto",
}

func init() { proto.RegisterFile("bot.proto", fileDescriptor_bot_38c84d5f33f64b69) }

var fileDescriptor_bot_38c84d5f33f64b69 = []byte{
	// 578 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x25, 0x4d, 0x69, 0xe3, 0x49, 0x82, 0xc4, 0xd2, 0x16, 0x37, 0x55, 0x21, 0xb8, 0x12, 0x54,
	0x42, 0x72, 0xa4, 0x80, 0x90, 0x10, 0x27, 0x8a, 0x7a, 0x24, 0x41, 0x49, 0x4b, 0x25, 0x2e, 0x96,
	0x5d, 0x6f, 0x12, 0x07, 0xaf, 0xc7, 0x78, 0xd7, 0xa9, 0xda, 0xdf, 0xe1, 0x9f, 0xf8, 0x01, 0x7e,
	0x04, 0x79, 0xbd, 0x0e, 0x71, 0x62, 0x9c, 0xf4, 0xc0, 0x75, 0xde, 0xcc, 0x7b, 0x33, 0xb3, 0x6f,
	0x07, 0x34, 0x07, 0x85, 0x19, 0x46, 0x28, 0x90, 0x34, 0xb8, 0xb0, 0x47, 0xa3, 0x29, 0xde, 0x9a,
	0x0e, 0x8a, 0xd6, 0xd1, 0x18, 0x71, 0xec, 0xd3, 0x8e, 0xc4, 0x9c, 0x78, 0xd4, 0xa1, 0x2c, 0x14,
	0xb7, 0x69, 0x6a, 0xeb, 0xf9, 0x32, 0x28, 0x3c, 0x46, 0xb9, 0xb0, 0x59, 0xa8, 0x12, 0x9a, 0xd7,
	0xc8, 0x42, 0x3b, 0x50, 0xf9, 0xc6, 0x57, 0xd8, 0xeb, 0x07, 0x0e, 0xda, 0x91, 0x7b, 0x85, 0xd1,
	0x77, 0x1a, 0x0d, 0xe8, 0x8f, 0x98, 0x72, 0x41, 0x5e, 0x40, 0x43, 0x25, 0x5a, 0x71, 0xec, 0xb9,
	0x7a, 0xa5, 0x5d, 0x39, 0xd5, 0x06, 0x75, 0x15, 0xbb, 0x8c, 0x3d, 0x97, 0x1c, 0x81, 0x16, 0x73,
	0x1a, 0xa5, 0xf8, 0x96, 0xc4, 0x6b, 0x49, 0x20, 0x01, 0x8d, 0x5f, 0x5b, 0x70, 0xfc, 0xd1, 0xa7,
	0x91, 0xe8, 0xd1, 0x9b, 0xe1, 0xc4, 0x1b, 0x89, 0x7e, 0x28, 0x3c, 0xe6, 0xdd, 0x51, 0x37, 0x53,
	0xc8, 0xca, 0x03, 0x9b, 0x51, 0x45, 0x2f, 0xcb, 0x7b, 0x36, 0xa3, 0xe4, 0x19, 0xd4, 0x25, 0x18,
	0x4e, 0xac, 0x20, 0x66, 0x8a, 0x5d, 0xe6, 0x7f, 0x99, 0xf4, 0x62, 0x46, 0x8e, 0x01, 0x24, 0x4e,
	0x99, 0xed, 0xf9, 0x7a, 0xf5, 0x2f, 0x7c, 0x9e, 0x04, 0xc8, 0x21, 0xd4, 0xa6, 0xe8, 0xa4, 0xd4,
	0xdb, 0x12, 0xdc, 0x9d, 0xa2, 0x23, 0x99, 0x4f, 0xa0, 0x29, 0xa8, 0xcd, 0xac, 0x64, 0x2f, 0x77,
	0x18, 0x50, 0xfd, 0xa1, 0xc4, 0x1b, 0x49, 0xf0, 0x42, 0xc5, 0xc8, 0x07, 0xa8, 0xf3, 0xa4, 0x69,
	0x8b, 0x0b, 0x3b, 0x12, 0xfa, 0x4e, 0xbb, 0x72, 0x5a, 0xef, 0xb6, 0xcc, 0x74, 0xb7, 0x66, 0xb6,
	0x5b, 0xf3, 0x22, 0xdb, 0xed, 0x00, 0x64, 0xfa, 0x30, 0xc9, 0x26, 0xef, 0x01, 0xb2, 0x62, 0x0c,
	0xf5, 0xdd, 0xb5, 0xb5, 0x9a, 0xaa, 0xc5, 0x70, 0x71, 0xeb, 0xb2, 0xf7, 0x5a, 0x6e, 0xeb, 0x49,
	0xff, 0x86, 0x07, 0x7b, 0xb9, 0xbd, 0x2e, 0xaf, 0x73, 0xe1, 0xb5, 0xe6, 0xaf, 0x41, 0xde, 0x82,
	0x16, 0xd0, 0x1b, 0x4b, 0x0a, 0xc9, 0x65, 0xd6, 0xbb, 0x4f, 0xcd, 0xb9, 0xa9, 0x32, 0x47, 0xa4,
	0x7c, 0xb5, 0x40, 0x31, 0x1b, 0x3e, 0xec, 0xe7, 0xa4, 0xf8, 0x46, 0x5a, 0xef, 0x00, 0xe6, 0x5a,
	0x5c, 0xdf, 0x6a, 0x57, 0xcb, 0xc4, 0xb4, 0x4c, 0x8c, 0x1b, 0x0c, 0x74, 0xa9, 0x36, 0xa0, 0x0c,
	0x67, 0xd4, 0xbd, 0xd7, 0x70, 0xe8, 0xbb, 0x1b, 0x0e, 0x87, 0x7e, 0xca, 0x6c, 0x84, 0x70, 0xb8,
	0x22, 0xb7, 0xf1, 0x80, 0x73, 0xbd, 0xf5, 0x03, 0x66, 0x82, 0xdc, 0xf8, 0x59, 0x51, 0x13, 0x7e,
	0x9a, 0xd8, 0xc1, 0xf8, 0xbf, 0x4f, 0x98, 0x7f, 0xf4, 0xea, 0x86, 0x8f, 0xde, 0xfd, 0xbd, 0x0d,
	0x70, 0x86, 0x62, 0x48, 0xa3, 0x99, 0x77, 0x4d, 0xc9, 0x67, 0x68, 0xe6, 0xee, 0x03, 0x31, 0xcc,
	0xc5, 0x63, 0x64, 0x16, 0x1d, 0x8f, 0xd6, 0xc1, 0x8a, 0xdb, 0xcf, 0x93, 0x13, 0x65, 0x3c, 0x48,
	0xe8, 0x72, 0x96, 0x5a, 0xa6, 0x2b, 0xb2, 0x76, 0x09, 0x9d, 0x05, 0x07, 0xc5, 0x47, 0x86, 0xbc,
	0x2e, 0xe1, 0x5d, 0x3e, 0x45, 0x25, 0x02, 0x7d, 0x78, 0x94, 0xff, 0x02, 0xe4, 0xa4, 0x84, 0x98,
	0xaf, 0x27, 0xbc, 0x84, 0xc7, 0x2b, 0xb6, 0x23, 0x2f, 0x0b, 0x38, 0x0b, 0xbe, 0x41, 0x09, 0xed,
	0x15, 0x90, 0x55, 0x37, 0x93, 0x57, 0x6b, 0x78, 0xef, 0xd1, 0xef, 0xa2, 0x67, 0x0b, 0xfb, 0x2d,
	0x30, 0xf5, 0xbf, 0x69, 0xcf, 0xf6, 0xbf, 0x3d, 0x99, 0x75, 0x73, 0x66, 0xec, 0x38, 0x28, 0x9c,
	0x1d, 0x99, 0xf8, 0xe6, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xa5, 0x1e, 0x48, 0xfc, 0x06,
	0x00, 0x00,
}
