// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package main // import "v2.staffjoy.com/account"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	ConfirmedAndActive   bool                 `protobuf:"varint,4,opt,name=confirmed_and_active,json=confirmedAndActive,proto3" json:"confirmed_and_active,omitempty"`
	MemberSince          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=member_since,json=memberSince,proto3" json:"member_since,omitempty"`
	Support              bool                 `protobuf:"varint,6,opt,name=support,proto3" json:"support,omitempty"`
	Phonenumber          string               `protobuf:"bytes,7,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	PhotoUrl             string               `protobuf:"bytes,8,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	PasswordHash         string               `protobuf:"bytes,9,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	PasswordSalt         string               `protobuf:"bytes,10,opt,name=password_salt,json=passwordSalt,proto3" json:"password_salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_d9c6a27162f64405, []int{0}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetConfirmedAndActive() bool {
	if m != nil {
		return m.ConfirmedAndActive
	}
	return false
}

func (m *Account) GetMemberSince() *timestamp.Timestamp {
	if m != nil {
		return m.MemberSince
	}
	return nil
}

func (m *Account) GetSupport() bool {
	if m != nil {
		return m.Support
	}
	return false
}

func (m *Account) GetPhonenumber() string {
	if m != nil {
		return m.Phonenumber
	}
	return ""
}

func (m *Account) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

func (m *Account) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func (m *Account) GetPasswordSalt() string {
	if m != nil {
		return m.PasswordSalt
	}
	return ""
}

type PhNumFNameEmail struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Phonenumber          string   `protobuf:"bytes,2,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	FName                string   `protobuf:"bytes,3,opt,name=f_name,json=fName,proto3" json:"f_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhNumFNameEmail) Reset()         { *m = PhNumFNameEmail{} }
func (m *PhNumFNameEmail) String() string { return proto.CompactTextString(m) }
func (*PhNumFNameEmail) ProtoMessage()    {}
func (*PhNumFNameEmail) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_d9c6a27162f64405, []int{1}
}
func (m *PhNumFNameEmail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhNumFNameEmail.Unmarshal(m, b)
}
func (m *PhNumFNameEmail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhNumFNameEmail.Marshal(b, m, deterministic)
}
func (dst *PhNumFNameEmail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhNumFNameEmail.Merge(dst, src)
}
func (m *PhNumFNameEmail) XXX_Size() int {
	return xxx_messageInfo_PhNumFNameEmail.Size(m)
}
func (m *PhNumFNameEmail) XXX_DiscardUnknown() {
	xxx_messageInfo_PhNumFNameEmail.DiscardUnknown(m)
}

var xxx_messageInfo_PhNumFNameEmail proto.InternalMessageInfo

func (m *PhNumFNameEmail) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PhNumFNameEmail) GetPhonenumber() string {
	if m != nil {
		return m.Phonenumber
	}
	return ""
}

func (m *PhNumFNameEmail) GetFName() string {
	if m != nil {
		return m.FName
	}
	return ""
}

type UpdatePasswordRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordRequest) Reset()         { *m = UpdatePasswordRequest{} }
func (m *UpdatePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordRequest) ProtoMessage()    {}
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_d9c6a27162f64405, []int{2}
}
func (m *UpdatePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordRequest.Unmarshal(m, b)
}
func (m *UpdatePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordRequest.Merge(dst, src)
}
func (m *UpdatePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordRequest.Size(m)
}
func (m *UpdatePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordRequest proto.InternalMessageInfo

func (m *UpdatePasswordRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UpdatePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type VerifyPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyPasswordRequest) Reset()         { *m = VerifyPasswordRequest{} }
func (m *VerifyPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyPasswordRequest) ProtoMessage()    {}
func (*VerifyPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_d9c6a27162f64405, []int{3}
}
func (m *VerifyPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyPasswordRequest.Unmarshal(m, b)
}
func (m *VerifyPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyPasswordRequest.Marshal(b, m, deterministic)
}
func (dst *VerifyPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyPasswordRequest.Merge(dst, src)
}
func (m *VerifyPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyPasswordRequest.Size(m)
}
func (m *VerifyPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyPasswordRequest proto.InternalMessageInfo

func (m *VerifyPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VerifyPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AccountList struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Limit                int32      `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32      `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AccountList) Reset()         { *m = AccountList{} }
func (m *AccountList) String() string { return proto.CompactTextString(m) }
func (*AccountList) ProtoMessage()    {}
func (*AccountList) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_d9c6a27162f64405, []int{4}
}
func (m *AccountList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountList.Unmarshal(m, b)
}
func (m *AccountList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountList.Marshal(b, m, deterministic)
}
func (dst *AccountList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountList.Merge(dst, src)
}
func (m *AccountList) XXX_Size() int {
	return xxx_messageInfo_AccountList.Size(m)
}
func (m *AccountList) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountList.DiscardUnknown(m)
}

var xxx_messageInfo_AccountList proto.InternalMessageInfo

func (m *AccountList) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *AccountList) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *AccountList) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetAccountListRequest struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountListRequest) Reset()         { *m = GetAccountListRequest{} }
func (m *GetAccountListRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountListRequest) ProtoMessage()    {}
func (*GetAccountListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_d9c6a27162f64405, []int{5}
}
func (m *GetAccountListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountListRequest.Unmarshal(m, b)
}
func (m *GetAccountListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountListRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountListRequest.Merge(dst, src)
}
func (m *GetAccountListRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountListRequest.Size(m)
}
func (m *GetAccountListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountListRequest proto.InternalMessageInfo

func (m *GetAccountListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetAccountListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type CreateAccountRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phonenumber          string   `protobuf:"bytes,3,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_d9c6a27162f64405, []int{6}
}
func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(dst, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateAccountRequest) GetPhonenumber() string {
	if m != nil {
		return m.Phonenumber
	}
	return ""
}

type GetAccountRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_d9c6a27162f64405, []int{7}
}
func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(dst, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type GetAccountByPhonenumberRequest struct {
	Phonenumber          string   `protobuf:"bytes,1,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountByPhonenumberRequest) Reset()         { *m = GetAccountByPhonenumberRequest{} }
func (m *GetAccountByPhonenumberRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountByPhonenumberRequest) ProtoMessage()    {}
func (*GetAccountByPhonenumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_d9c6a27162f64405, []int{8}
}
func (m *GetAccountByPhonenumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountByPhonenumberRequest.Unmarshal(m, b)
}
func (m *GetAccountByPhonenumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountByPhonenumberRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountByPhonenumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountByPhonenumberRequest.Merge(dst, src)
}
func (m *GetAccountByPhonenumberRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountByPhonenumberRequest.Size(m)
}
func (m *GetAccountByPhonenumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountByPhonenumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountByPhonenumberRequest proto.InternalMessageInfo

func (m *GetAccountByPhonenumberRequest) GetPhonenumber() string {
	if m != nil {
		return m.Phonenumber
	}
	return ""
}

type PasswordResetRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordResetRequest) Reset()         { *m = PasswordResetRequest{} }
func (m *PasswordResetRequest) String() string { return proto.CompactTextString(m) }
func (*PasswordResetRequest) ProtoMessage()    {}
func (*PasswordResetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_d9c6a27162f64405, []int{9}
}
func (m *PasswordResetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordResetRequest.Unmarshal(m, b)
}
func (m *PasswordResetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordResetRequest.Marshal(b, m, deterministic)
}
func (dst *PasswordResetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordResetRequest.Merge(dst, src)
}
func (m *PasswordResetRequest) XXX_Size() int {
	return xxx_messageInfo_PasswordResetRequest.Size(m)
}
func (m *PasswordResetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordResetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordResetRequest proto.InternalMessageInfo

func (m *PasswordResetRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type EmailChangeRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailChangeRequest) Reset()         { *m = EmailChangeRequest{} }
func (m *EmailChangeRequest) String() string { return proto.CompactTextString(m) }
func (*EmailChangeRequest) ProtoMessage()    {}
func (*EmailChangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_d9c6a27162f64405, []int{10}
}
func (m *EmailChangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailChangeRequest.Unmarshal(m, b)
}
func (m *EmailChangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailChangeRequest.Marshal(b, m, deterministic)
}
func (dst *EmailChangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailChangeRequest.Merge(dst, src)
}
func (m *EmailChangeRequest) XXX_Size() int {
	return xxx_messageInfo_EmailChangeRequest.Size(m)
}
func (m *EmailChangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailChangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailChangeRequest proto.InternalMessageInfo

func (m *EmailChangeRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EmailChangeRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type EmailConfirmation struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailConfirmation) Reset()         { *m = EmailConfirmation{} }
func (m *EmailConfirmation) String() string { return proto.CompactTextString(m) }
func (*EmailConfirmation) ProtoMessage()    {}
func (*EmailConfirmation) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_d9c6a27162f64405, []int{11}
}
func (m *EmailConfirmation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailConfirmation.Unmarshal(m, b)
}
func (m *EmailConfirmation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailConfirmation.Marshal(b, m, deterministic)
}
func (dst *EmailConfirmation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailConfirmation.Merge(dst, src)
}
func (m *EmailConfirmation) XXX_Size() int {
	return xxx_messageInfo_EmailConfirmation.Size(m)
}
func (m *EmailConfirmation) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailConfirmation.DiscardUnknown(m)
}

var xxx_messageInfo_EmailConfirmation proto.InternalMessageInfo

func (m *EmailConfirmation) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EmailConfirmation) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetOrCreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phonenumber          string   `protobuf:"bytes,3,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrCreateRequest) Reset()         { *m = GetOrCreateRequest{} }
func (m *GetOrCreateRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrCreateRequest) ProtoMessage()    {}
func (*GetOrCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_d9c6a27162f64405, []int{12}
}
func (m *GetOrCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrCreateRequest.Unmarshal(m, b)
}
func (m *GetOrCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrCreateRequest.Marshal(b, m, deterministic)
}
func (dst *GetOrCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrCreateRequest.Merge(dst, src)
}
func (m *GetOrCreateRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrCreateRequest.Size(m)
}
func (m *GetOrCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrCreateRequest proto.InternalMessageInfo

func (m *GetOrCreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetOrCreateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetOrCreateRequest) GetPhonenumber() string {
	if m != nil {
		return m.Phonenumber
	}
	return ""
}

type TrackEventRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Event                string   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackEventRequest) Reset()         { *m = TrackEventRequest{} }
func (m *TrackEventRequest) String() string { return proto.CompactTextString(m) }
func (*TrackEventRequest) ProtoMessage()    {}
func (*TrackEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_d9c6a27162f64405, []int{13}
}
func (m *TrackEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackEventRequest.Unmarshal(m, b)
}
func (m *TrackEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackEventRequest.Marshal(b, m, deterministic)
}
func (dst *TrackEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackEventRequest.Merge(dst, src)
}
func (m *TrackEventRequest) XXX_Size() int {
	return xxx_messageInfo_TrackEventRequest.Size(m)
}
func (m *TrackEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrackEventRequest proto.InternalMessageInfo

func (m *TrackEventRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *TrackEventRequest) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

type SyncUserRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncUserRequest) Reset()         { *m = SyncUserRequest{} }
func (m *SyncUserRequest) String() string { return proto.CompactTextString(m) }
func (*SyncUserRequest) ProtoMessage()    {}
func (*SyncUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_d9c6a27162f64405, []int{14}
}
func (m *SyncUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncUserRequest.Unmarshal(m, b)
}
func (m *SyncUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncUserRequest.Marshal(b, m, deterministic)
}
func (dst *SyncUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncUserRequest.Merge(dst, src)
}
func (m *SyncUserRequest) XXX_Size() int {
	return xxx_messageInfo_SyncUserRequest.Size(m)
}
func (m *SyncUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncUserRequest proto.InternalMessageInfo

func (m *SyncUserRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*Account)(nil), "account.Account")
	proto.RegisterType((*PhNumFNameEmail)(nil), "account.PhNumFNameEmail")
	proto.RegisterType((*UpdatePasswordRequest)(nil), "account.UpdatePasswordRequest")
	proto.RegisterType((*VerifyPasswordRequest)(nil), "account.VerifyPasswordRequest")
	proto.RegisterType((*AccountList)(nil), "account.AccountList")
	proto.RegisterType((*GetAccountListRequest)(nil), "account.GetAccountListRequest")
	proto.RegisterType((*CreateAccountRequest)(nil), "account.CreateAccountRequest")
	proto.RegisterType((*GetAccountRequest)(nil), "account.GetAccountRequest")
	proto.RegisterType((*GetAccountByPhonenumberRequest)(nil), "account.GetAccountByPhonenumberRequest")
	proto.RegisterType((*PasswordResetRequest)(nil), "account.PasswordResetRequest")
	proto.RegisterType((*EmailChangeRequest)(nil), "account.EmailChangeRequest")
	proto.RegisterType((*EmailConfirmation)(nil), "account.EmailConfirmation")
	proto.RegisterType((*GetOrCreateRequest)(nil), "account.GetOrCreateRequest")
	proto.RegisterType((*TrackEventRequest)(nil), "account.TrackEventRequest")
	proto.RegisterType((*SyncUserRequest)(nil), "account.SyncUserRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	Create(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*Account, error)
	List(ctx context.Context, in *GetAccountListRequest, opts ...grpc.CallOption) (*AccountList, error)
	Get(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error)
	Update(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error)
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetPhNumFNameEmail(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*PhNumFNameEmail, error)
	RequestPasswordReset(ctx context.Context, in *PasswordResetRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RequestEmailChange(ctx context.Context, in *EmailChangeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	VerifyPassword(ctx context.Context, in *VerifyPasswordRequest, opts ...grpc.CallOption) (*Account, error)
	ChangeEmail(ctx context.Context, in *EmailConfirmation, opts ...grpc.CallOption) (*empty.Empty, error)
	GetOrCreate(ctx context.Context, in *GetOrCreateRequest, opts ...grpc.CallOption) (*Account, error)
	GetAccountByPhonenumber(ctx context.Context, in *GetAccountByPhonenumberRequest, opts ...grpc.CallOption) (*Account, error)
	TrackEvent(ctx context.Context, in *TrackEventRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	SyncUser(ctx context.Context, in *SyncUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) Create(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/account.AccountService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) List(ctx context.Context, in *GetAccountListRequest, opts ...grpc.CallOption) (*AccountList, error) {
	out := new(AccountList)
	err := c.cc.Invoke(ctx, "/account.AccountService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Get(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/account.AccountService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Update(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/account.AccountService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.AccountService/UpdatePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetPhNumFNameEmail(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*PhNumFNameEmail, error) {
	out := new(PhNumFNameEmail)
	err := c.cc.Invoke(ctx, "/account.AccountService/GetPhNumFNameEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) RequestPasswordReset(ctx context.Context, in *PasswordResetRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.AccountService/RequestPasswordReset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) RequestEmailChange(ctx context.Context, in *EmailChangeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.AccountService/RequestEmailChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) VerifyPassword(ctx context.Context, in *VerifyPasswordRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/account.AccountService/VerifyPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ChangeEmail(ctx context.Context, in *EmailConfirmation, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.AccountService/ChangeEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetOrCreate(ctx context.Context, in *GetOrCreateRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/account.AccountService/GetOrCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccountByPhonenumber(ctx context.Context, in *GetAccountByPhonenumberRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/account.AccountService/GetAccountByPhonenumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) TrackEvent(ctx context.Context, in *TrackEventRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.AccountService/TrackEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) SyncUser(ctx context.Context, in *SyncUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.AccountService/SyncUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	Create(context.Context, *CreateAccountRequest) (*Account, error)
	List(context.Context, *GetAccountListRequest) (*AccountList, error)
	Get(context.Context, *GetAccountRequest) (*Account, error)
	Update(context.Context, *Account) (*Account, error)
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*empty.Empty, error)
	GetPhNumFNameEmail(context.Context, *GetAccountRequest) (*PhNumFNameEmail, error)
	RequestPasswordReset(context.Context, *PasswordResetRequest) (*empty.Empty, error)
	RequestEmailChange(context.Context, *EmailChangeRequest) (*empty.Empty, error)
	VerifyPassword(context.Context, *VerifyPasswordRequest) (*Account, error)
	ChangeEmail(context.Context, *EmailConfirmation) (*empty.Empty, error)
	GetOrCreate(context.Context, *GetOrCreateRequest) (*Account, error)
	GetAccountByPhonenumber(context.Context, *GetAccountByPhonenumberRequest) (*Account, error)
	TrackEvent(context.Context, *TrackEventRequest) (*empty.Empty, error)
	SyncUser(context.Context, *SyncUserRequest) (*empty.Empty, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Create(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).List(ctx, req.(*GetAccountListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Get(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Update(ctx, req.(*Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/UpdatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdatePassword(ctx, req.(*UpdatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetPhNumFNameEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetPhNumFNameEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/GetPhNumFNameEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetPhNumFNameEmail(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_RequestPasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).RequestPasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/RequestPasswordReset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).RequestPasswordReset(ctx, req.(*PasswordResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_RequestEmailChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).RequestEmailChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/RequestEmailChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).RequestEmailChange(ctx, req.(*EmailChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_VerifyPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).VerifyPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/VerifyPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).VerifyPassword(ctx, req.(*VerifyPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ChangeEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailConfirmation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ChangeEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/ChangeEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ChangeEmail(ctx, req.(*EmailConfirmation))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetOrCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetOrCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/GetOrCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetOrCreate(ctx, req.(*GetOrCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAccountByPhonenumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountByPhonenumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccountByPhonenumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/GetAccountByPhonenumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccountByPhonenumber(ctx, req.(*GetAccountByPhonenumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_TrackEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).TrackEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/TrackEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).TrackEvent(ctx, req.(*TrackEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_SyncUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SyncUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/SyncUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SyncUser(ctx, req.(*SyncUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AccountService_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AccountService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AccountService_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AccountService_Update_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _AccountService_UpdatePassword_Handler,
		},
		{
			MethodName: "GetPhNumFNameEmail",
			Handler:    _AccountService_GetPhNumFNameEmail_Handler,
		},
		{
			MethodName: "RequestPasswordReset",
			Handler:    _AccountService_RequestPasswordReset_Handler,
		},
		{
			MethodName: "RequestEmailChange",
			Handler:    _AccountService_RequestEmailChange_Handler,
		},
		{
			MethodName: "VerifyPassword",
			Handler:    _AccountService_VerifyPassword_Handler,
		},
		{
			MethodName: "ChangeEmail",
			Handler:    _AccountService_ChangeEmail_Handler,
		},
		{
			MethodName: "GetOrCreate",
			Handler:    _AccountService_GetOrCreate_Handler,
		},
		{
			MethodName: "GetAccountByPhonenumber",
			Handler:    _AccountService_GetAccountByPhonenumber_Handler,
		},
		{
			MethodName: "TrackEvent",
			Handler:    _AccountService_TrackEvent_Handler,
		},
		{
			MethodName: "SyncUser",
			Handler:    _AccountService_SyncUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_account_d9c6a27162f64405) }

var fileDescriptor_account_d9c6a27162f64405 = []byte{
	// 1046 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xae, 0xfb, 0x93, 0xa6, 0x27, 0x6d, 0xb6, 0x1d, 0x92, 0xd6, 0xb8, 0xdb, 0x38, 0x3b, 0x62,
	0xd5, 0x6a, 0x05, 0x89, 0x08, 0x12, 0x17, 0x8b, 0x76, 0xa5, 0xa6, 0x94, 0x82, 0xa8, 0x76, 0x2b,
	0x77, 0xbb, 0x17, 0x08, 0x29, 0xeb, 0x24, 0x93, 0xc4, 0x10, 0xff, 0xac, 0x3d, 0x0e, 0x8a, 0x10,
	0x37, 0x3c, 0x01, 0x12, 0x8f, 0xc2, 0x4b, 0xec, 0x25, 0x12, 0xf7, 0x06, 0x55, 0x3c, 0x41, 0x9e,
	0x00, 0xcd, 0x78, 0x9c, 0x38, 0xc9, 0xc4, 0x12, 0x17, 0x7b, 0x97, 0x33, 0xe7, 0xfb, 0xbe, 0x33,
	0x73, 0xfe, 0x1c, 0xd8, 0x33, 0x3b, 0x1d, 0x37, 0x74, 0x68, 0xcd, 0xf3, 0x5d, 0xea, 0xa2, 0x6d,
	0x61, 0x6a, 0x0f, 0xfb, 0xae, 0xdb, 0x1f, 0x92, 0xba, 0xe9, 0x59, 0x75, 0xd3, 0x71, 0x5c, 0x6a,
	0x52, 0xcb, 0x75, 0x82, 0x18, 0xa6, 0xe9, 0xc2, 0xcb, 0xad, 0x76, 0xd8, 0xab, 0x53, 0xcb, 0x26,
	0x01, 0x35, 0x6d, 0x4f, 0x00, 0x8e, 0x17, 0x01, 0xc4, 0xf6, 0xe8, 0x58, 0x38, 0x3f, 0xe9, 0x5b,
	0x74, 0x10, 0xb6, 0x6b, 0x1d, 0xd7, 0xae, 0xf7, 0xdd, 0xbe, 0x3b, 0x43, 0x31, 0x8b, 0x1b, 0xfc,
	0x57, 0x0c, 0xc7, 0x7f, 0x6c, 0xc2, 0xf6, 0x79, 0x7c, 0x2d, 0xf4, 0x08, 0x36, 0xc3, 0xd0, 0xea,
	0xaa, 0x4a, 0x55, 0x39, 0xdb, 0x69, 0xee, 0x4d, 0x22, 0x7d, 0xa7, 0xdb, 0x7e, 0x8a, 0xd9, 0x19,
	0x36, 0xb8, 0x8b, 0x41, 0x1c, 0xd3, 0x26, 0xea, 0xfa, 0x3c, 0x84, 0x9d, 0x61, 0x83, 0xbb, 0xd0,
	0x47, 0xb0, 0x45, 0x6c, 0xd3, 0x1a, 0xaa, 0x1b, 0x1c, 0x53, 0x9c, 0x44, 0x3a, 0x30, 0x0c, 0x3f,
	0xc4, 0x46, 0xec, 0x44, 0x2f, 0xa1, 0xd4, 0x71, 0x9d, 0x9e, 0xe5, 0xdb, 0xa4, 0xdb, 0x32, 0x9d,
	0x6e, 0xcb, 0xec, 0x50, 0x6b, 0x44, 0xd4, 0xcd, 0xaa, 0x72, 0x96, 0x6f, 0x9e, 0x4c, 0x22, 0xfd,
	0x43, 0x46, 0x92, 0x61, 0xb0, 0x81, 0xa6, 0xc7, 0xe7, 0x4e, 0xf7, 0x9c, 0x1f, 0xa2, 0xef, 0x61,
	0xd7, 0x26, 0x76, 0x9b, 0xf8, 0xad, 0xc0, 0x72, 0x3a, 0x44, 0xdd, 0xaa, 0x2a, 0x67, 0x85, 0x86,
	0x56, 0x8b, 0x73, 0x55, 0x4b, 0xb2, 0x50, 0x7b, 0x95, 0x24, 0xb3, 0x79, 0xf2, 0x2e, 0xd2, 0xd7,
	0x26, 0x91, 0x7e, 0xc0, 0x02, 0xa5, 0xb9, 0xf8, 0xb7, 0xbf, 0x75, 0xc5, 0x28, 0xc4, 0x47, 0xb7,
	0xec, 0x04, 0x3d, 0x81, 0xed, 0x20, 0xf4, 0x3c, 0xd7, 0xa7, 0x6a, 0x8e, 0xdf, 0x70, 0x7f, 0x12,
	0xe9, 0xbb, 0x8c, 0x28, 0x8e, 0xb1, 0x91, 0x00, 0xd0, 0xe7, 0x50, 0xf0, 0x06, 0xae, 0x43, 0x9c,
	0x90, 0xf1, 0xd5, 0x6d, 0x9e, 0x86, 0xd2, 0x24, 0xd2, 0xf7, 0x19, 0x3e, 0xe5, 0xc2, 0x46, 0x1a,
	0x88, 0xea, 0xb0, 0xe3, 0x0d, 0x5c, 0xea, 0xb6, 0x42, 0x7f, 0xa8, 0xe6, 0x39, 0x0b, 0x4d, 0x22,
	0xbd, 0x28, 0x58, 0xb1, 0x03, 0x1b, 0x79, 0xfe, 0xfb, 0xce, 0x1f, 0xa2, 0x2f, 0x60, 0xcf, 0x33,
	0x83, 0xe0, 0x27, 0xd7, 0xef, 0xb6, 0x06, 0x66, 0x30, 0x50, 0x77, 0x38, 0xe9, 0x70, 0x12, 0xe9,
	0x88, 0x93, 0xd2, 0x4e, 0x6c, 0xec, 0x26, 0xf6, 0xd7, 0x66, 0x30, 0x98, 0x23, 0x07, 0xe6, 0x90,
	0xaa, 0xb0, 0x82, 0xcc, 0x9c, 0x29, 0xf2, 0x2d, 0x33, 0xdf, 0xc0, 0x83, 0x9b, 0xc1, 0x8b, 0xd0,
	0xfe, 0xea, 0x85, 0x69, 0x93, 0x4b, 0x5e, 0xd0, 0x52, 0x52, 0x76, 0xde, 0x3d, 0x49, 0x99, 0xab,
	0xf3, 0xb9, 0xe0, 0x6d, 0x33, 0xff, 0xea, 0x32, 0xe4, 0x7a, 0x2d, 0xde, 0x53, 0x1b, 0x31, 0xb1,
	0xc7, 0x34, 0xf1, 0x15, 0x94, 0xef, 0xbc, 0xae, 0x49, 0xc9, 0x8d, 0x88, 0x6b, 0x90, 0xb7, 0x21,
	0x09, 0x28, 0x42, 0xe9, 0x26, 0x15, 0x5d, 0xa9, 0x41, 0x3e, 0xb9, 0x9e, 0x08, 0x31, 0xb5, 0xf1,
	0x37, 0x50, 0x7e, 0x4d, 0x7c, 0xab, 0x37, 0x5e, 0x14, 0x92, 0x5f, 0x38, 0x4b, 0xca, 0x85, 0x82,
	0x18, 0x95, 0x6b, 0x2b, 0xa0, 0xa8, 0x01, 0x79, 0x31, 0xd0, 0x81, 0xaa, 0x54, 0x37, 0xce, 0x0a,
	0x8d, 0xfd, 0x5a, 0x32, 0xf0, 0x02, 0xd7, 0xdc, 0x64, 0x3d, 0x66, 0x4c, 0x71, 0x2c, 0xe8, 0xd0,
	0xb2, 0x2d, 0xca, 0xb5, 0xb7, 0x8c, 0xd8, 0x40, 0x87, 0x90, 0x73, 0x7b, 0xbd, 0x80, 0x50, 0x9e,
	0x83, 0x2d, 0x43, 0x58, 0xf8, 0x12, 0xca, 0x57, 0x84, 0xa6, 0x62, 0x26, 0x77, 0x9f, 0x11, 0x94,
	0x34, 0x41, 0x2e, 0x8f, 0xdb, 0x50, 0xba, 0xf0, 0x89, 0x49, 0x89, 0x50, 0x4a, 0xa5, 0x92, 0x27,
	0x5e, 0xa4, 0x92, 0x4f, 0xef, 0x34, 0x2b, 0xeb, 0x19, 0x65, 0xdc, 0x58, 0x2a, 0x23, 0x3e, 0x85,
	0x83, 0xd9, 0x55, 0x33, 0x6a, 0x85, 0x9b, 0x50, 0x99, 0x01, 0x9b, 0xe3, 0x9b, 0x99, 0x46, 0xc2,
	0x5a, 0x08, 0xa6, 0x2c, 0x07, 0xfb, 0x18, 0x4a, 0xb3, 0x6a, 0x06, 0x84, 0x66, 0x96, 0x14, 0x3f,
	0x07, 0xc4, 0x5b, 0xf4, 0x62, 0x60, 0x3a, 0x7d, 0x92, 0xd5, 0x47, 0xd2, 0xc7, 0xe3, 0x67, 0x70,
	0x10, 0xf3, 0xe3, 0xa5, 0xc3, 0x77, 0xf5, 0xff, 0xa0, 0xbf, 0x01, 0x74, 0x45, 0xe8, 0x4b, 0x3f,
	0x2e, 0xc1, 0xfb, 0xc8, 0xfd, 0x33, 0x38, 0x78, 0xe5, 0x9b, 0x9d, 0x1f, 0x2f, 0x47, 0x24, 0x33,
	0xf7, 0x3c, 0x00, 0xc3, 0x4c, 0x03, 0x30, 0x03, 0x3f, 0x86, 0x07, 0xb7, 0x63, 0xa7, 0x73, 0x17,
	0xcc, 0x4a, 0x20, 0x21, 0x37, 0xa2, 0x3c, 0x14, 0x45, 0xd9, 0x6e, 0x89, 0x3f, 0xb2, 0x3a, 0x04,
	0x19, 0x90, 0x8b, 0x5f, 0x85, 0x4e, 0xa6, 0x9d, 0x2f, 0xeb, 0x34, 0x6d, 0x69, 0x30, 0xf0, 0xd1,
	0xaf, 0x7f, 0xfd, 0xfb, 0xfb, 0xfa, 0x01, 0xde, 0xad, 0x8f, 0x3e, 0xad, 0x27, 0xe3, 0xf1, 0x54,
	0x79, 0x82, 0x0c, 0xd8, 0xe4, 0xd3, 0x55, 0x99, 0x52, 0xa4, 0x23, 0xa0, 0x95, 0x16, 0x25, 0x99,
	0x13, 0x97, 0xb8, 0x6c, 0x11, 0xcd, 0xc9, 0xa2, 0x1b, 0xd8, 0xb8, 0x22, 0x14, 0x69, 0x12, 0xc9,
	0xd5, 0x37, 0x3c, 0xe6, 0x52, 0x65, 0xf4, 0x41, 0x5a, 0xaa, 0xfe, 0x33, 0xcb, 0xc5, 0x2f, 0xe8,
	0x1a, 0x72, 0xf1, 0x7a, 0x42, 0x4b, 0x44, 0x89, 0x54, 0x85, 0x4b, 0xa9, 0x9a, 0x4c, 0x8a, 0xbd,
	0xf9, 0x2d, 0x14, 0xe7, 0x97, 0x5d, 0xea, 0xf5, 0xd2, 0x2d, 0xa8, 0x1d, 0x2e, 0x7d, 0xd7, 0x2e,
	0xd9, 0x7f, 0x00, 0x7c, 0xca, 0x23, 0x3d, 0xd2, 0x1e, 0x4a, 0x22, 0xd5, 0x93, 0x45, 0xc6, 0x42,
	0x5e, 0xf3, 0xae, 0x5c, 0x5c, 0xe2, 0x59, 0x19, 0x52, 0xa7, 0xbe, 0x05, 0x16, 0x5e, 0x63, 0x5f,
	0x73, 0x01, 0x9b, 0x9b, 0xcb, 0x54, 0x5b, 0xc8, 0xe6, 0x75, 0xe5, 0x2b, 0xd6, 0xd0, 0xb7, 0x80,
	0x04, 0x28, 0x35, 0xba, 0xe8, 0x78, 0x2a, 0xb7, 0x3c, 0xd0, 0x19, 0x62, 0x5f, 0x42, 0x71, 0xfe,
	0x13, 0x90, 0x4a, 0xaf, 0xf4, 0xdb, 0x20, 0x29, 0xe1, 0x1a, 0xba, 0x80, 0x42, 0x1c, 0x70, 0x31,
	0x55, 0x4b, 0xcb, 0x21, 0xe3, 0x2a, 0xcf, 0xa1, 0x90, 0x5a, 0x06, 0xa9, 0x07, 0x2d, 0xaf, 0x08,
	0xe9, 0x25, 0x5e, 0xc3, 0xd1, 0x8a, 0xed, 0x89, 0x4e, 0x25, 0xb5, 0x93, 0xed, 0x57, 0xa9, 0x6e,
	0x13, 0x60, 0xb6, 0x42, 0x52, 0x6f, 0x5b, 0xda, 0x2b, 0x99, 0x6f, 0xcb, 0x27, 0x7b, 0x04, 0xcd,
	0x9a, 0x65, 0x61, 0xb5, 0xac, 0xe6, 0x37, 0x1f, 0xbf, 0xbb, 0xaf, 0x28, 0x7f, 0xde, 0x57, 0x94,
	0x7f, 0xee, 0x2b, 0xca, 0x77, 0x47, 0xa3, 0x46, 0x2d, 0xa0, 0x66, 0xaf, 0xf7, 0x83, 0x3b, 0xe6,
	0x7f, 0x66, 0x85, 0x60, 0x3b, 0xc7, 0x89, 0x9f, 0xfd, 0x17, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x8a,
	0x18, 0x6e, 0x5d, 0x0b, 0x00, 0x00,
}
